drop table if exists test_entity;
create table if not exists test_entity
(
    id          int generated by default as identity primary key,
    created_at  timestamp with time zone,
    text_column varchar,
    json_column jsonb
);
